services:
  - type: web
    name: spaceship-architect-atb-sync
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 24
